name: Go Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-version: '1.23.4'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Configure Environment
        run: echo "GOEXPERIMENT=aliastypeparams" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
