# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    needs: setup
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: aliastypeparams
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: go build -v ./...

  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: aliastypeparams
      GODEBUG: gotypesalias=1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Test
        run: go test -v ./...
