# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/setup.yml

    steps:
      - name: Build
        run: go build -v ./...

  test:
    uses: ./.github/workflows/setup.yml

    steps:
      - name: Test
        run: go test -v ./...
